### ISSUE TITLE
Support predis

### ISSUE THREAD

**Issue by tarjei** [oleh-ozimok/php-centrifugo#2]
Hi, Predis (https://github.com/nrk/predis) is a Redis wrapper that is very common to use. It would be very nice if this library could support it.

**Comment by oleh-ozimok** [comment]
Hi, I will add support on next week

**Comment by tarjei** [comment]
Hi, Any news on this?  :P

**Comment by oleh-ozimok** [comment]
@tarjei still relevant?

**Comment by wendel841** [comment]
I think its great feature to integrate predis.

**Comment by oleh-ozimok** [comment]
Done, details in the [documentation](https://github.com/oleh-ozimok/php-centrifugo)

**Comment by tarjei** [comment]
Good work!
