### ISSUE TITLE
Redis AUTH

### ISSUE THREAD

**Issue by maksimusyan** [oleh-ozimok/php-centrifugo#6]
Hi, when using the Redis protocol, you can not use authorization?
Please add the method AUTH through the config:
``` php
'redis' => [
   'host'         => 'localhost',
   'port'         => 6379,
   'db'           => 0,
   'shardsNumber' => 0,
   'auth' => 'YOUR_AUTH_TOKEN'
],
```

**Comment by breitsmiley** [comment]
+1

**Comment by maksimusyan** [comment]
@breitsmiley, I did not wait and did fork
You can use :)

**Comment by oleh-ozimok** [comment]
Sorry guys do not have much time. I added support for the authentication

**Comment by breitsmiley** [comment]
@oleh-ozimok Thanks for your work. 
Can you also update package version on packagist.org ?

**Comment by oleh-ozimok** [comment]
Done
чт, 22 марта 2018 г. в 10:49, breitsmiley <notifications@github.com>:
